



services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: marketplace
    ports:
        - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql

