/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "API": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "BcvBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "BcvFunction": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "BcvQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "DakaWebApp": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "GolangApi": {
      "name": string
      "type": "sst.aws.Function"
    }
    "JavaService": {
      "service": string
      "type": "sst.aws.Service"
    }
    "MyBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "MyDatabase": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Mysql"
      "username": string
    }
    "MyRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "MyVpc": {
      "type": "sst.aws.Vpc"
    }
    "ProcessBcvFile": {
      "name": string
      "type": "sst.aws.Function"
    }
    "WebAssetsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}