/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/// <reference types="vite/client" />
interface ImportMetaEnv {
  readonly VITE_IS_DEV: string
  readonly VITE_GOLANG_API_URL: string
}
interface ImportMeta {
  readonly env: ImportMetaEnv
}